# Workflow derived from https://github.com/r-lib/actions/tree/master/examples

name: sync math.utah.edu fishery-journals

# Run every Monday at 1 pm UTC
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2

      - name: get last commit msg
        id: commit-msg
        run: |
          git tag
          last_commit_msg=$(git log -1 --pretty=%B)
          echo "::set-output name=msg::${last_commit_msg}"
          
      - name: Fetch list of journals
        run: wget http://www.math.edu/~beebe/.fishery-journals/fishery-journals.txt
      -name: Move list of journals to inst/math.utah.edu
        run: mv fishery-journal.txt inst/math.utah.edu/fishery-journals.txt
      - name: Fetch files
        run: for f in ` cat inst/math.utah.edu/fish*txt `; do rsync -av rsync://ftp.math.utah.edu/bib/$f ./inst/math.utah.edu/$f; done
        
      - name: Create Pull Request
        if: ${{ !contains(steps.commit-msg.outputs.msg, 'run')}}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Updates fishery-journal files'
          branch: download
          title: 'Updates fishery-journal files'
          body: |
           Auto-generated by [download.yml][1]
             [1]: https://github.com/kellijohnson-NOAA/journals/tree/main/.github/workflows/download.yml